### ISSUE TITLE
Используйте return (short circuit) вместо цепочки условий

### ISSUE THREAD

**Issue by coursar** [pentogono/sportmaster-bonus-service#3]
https://github.com/pentogono/sportmaster-bonus-service/blob/46aa3fde224e1563b2b1f177fa7aca4fa65cfff2/src/main/java/ru/itpark/SportmasterBonusService.java#L17-L26

**Comment by pentogono** [comment]
@coursar f69f211203882a1dd016a25555177a2c52f9ab87
